### PR TITLE
Add decode event type to other DecoderStates to support filtering.

### PR DESCRIPTION
**Pull request by VolFFProCoder**
This is in addition to [Add filter button to messages #1098](https://github.com/DSheirer/sdrtrunk/pull/1098).

This adds the event type to allow for filtering of the remaining system protocols.

### CODE REVIEW

**Comment by DSheirer** [comment]
@VolFFProCoder my apologies for the delay in merging your PRs.  I merged the first PR that adds the filter and clear button panel.  

Could you please squash your commits and rebase onto master so that I can merge this one.

**Comment by VolFFProCoder** [comment]
Good Evening,

I am attempting to squash the commits. Git is not my best tech. I only use
a few simple commands in IntelliJ for 99% of my GitHub interactions. I used
IntelliJ to rebase master onto my branch. It looks like it just merged a
bunch of commits. I am not sure if I did it correctly. It also looks like
it added some additional changes that I had on my local master branch. I
also had some code that I had to merge. I deployed the app and verified
that the app still functions correctly and all event related tabs also
function correctly. I only have P25 Phase 1 in my area to verify
functionality. If you can give me some pointers, it would be much
appreciated.

Thanks,
Chris

**Comment by DSheirer** [comment]
The process I use is to squash your commits first and then do a force-push to sync the remote branch with your local branch.  IntelliJ makes squashing easy by selecting all of the commits you want to squash in the Git:Log view and then right-click squash. 

Now that you have your local & remote repo changes (squashed) into a single commit, rebase your branch onto master, so that your single commit sits on top of the latest master branch commit.

That's it.

But, if you've rebased onto master (or rebased master onto your branch) in the middle of a bunch of commits and some of the classes that you change are also changed on master, then it gets messy with your commit history looking like a spider web.

With 20 commits, I would sometimes recommend:

1. Create/checkout a fresh new branch from the latest master.
2. Use Intelli-J's Git history view and filter it to see the commit history of your existing branch.
3. Select each commit, oldest to newest, from your original branch and use the 'Cherry Pick' to copy that commit onto your new clean branch.
4. Work through each of your 20 commits.

In the end, you'll have a fresh branch from master with your 20 commits cleanly layered on top.  Then you can 'squash' and 'force push'  and then your branch is ready for merge.

Don't spend too much time on this ... if you can't get it, let me know and I can knock it out fairly quickly for you.

Git is easy to use once you've figured it out ... but getting to that point of knowing how to use it is a challenge for everyone.

**Comment by VolFFProCoder** [comment]
I attempted to squash the commits, but it is in a state that even intellij
won't do anything. I tried creating a new branch from origin/master, but it
just reverts to the local master (with all the changes still in it). If you
are able to make the changes, I would appreciate it. I don't want to mess
it up any more than I already have. I noticed in the history that the
branch only shows one entry in the log. This workflow is different from my
usual commit process at work. I will make sure I squash future commits
before pushing up. I sincerely apologize for any inconveniences I have
caused. I am still getting used to git and contributing to open source
projects (this one is the first one I have found interesting and worthy of
my time). I use it almost on a daily basis listening while I work from
home. This is some really cool software, and I hope to contribute further.
If you have any suggestions, please let me know.

Thanks again,
Chris

**Comment by apankowski** [comment]
@VolFFProCoder do you need help in either (or both):

1. rebasing your PR on top of master?
2. finishing the PR due to conflicts in master?

**Comment by DSheirer** [comment]
@VolFFProCoder I created a new branch from master and cherry-picked all of your commits from the PR and squashed into a single commit.   If you could checkout this branch and confirm that it functions correctly according to the way that you implemented it.

**Question:** What is the purpose of the newly added 'Last Seen' and 'Last Heard' tabs that were added to the Now Playing panel?  

When I ran the code, these tabs were partially populated with a few events and the only filtering options were the 'Icon' that was assigned to the event.

**Comment by VolFFProCoder** [comment]
I have confirmed that the changes in the branch still work after resolving some merge conflicts.
The intent of the feature is to capture events when a radio ID becomes active. This is to allow the user to monitor their favorite radio group identified by the icon type. Before, it was difficult to determine if any radio has been active on the system because the events are numerous and buffer is cleared often. Last Seen and Last Heard provides a list of events of registration or when audio is transmitted.

**Comment by DSheirer** [comment]
Closing.  Contents of this PR were merged under PR #1601

**Pull request closed without merging**
