### PR TITLE
Yet Another Headless patch

### PR DESCRIPTION
**Pull request by ImagoTrigger**
not so crappy this time #92 4 years later

### CODE REVIEW

**Comment by n2cr** [comment]
Please Denny can you pull this into the trunk before 0.5.0 is released.

**Comment by ImagoTrigger** [comment]
its been runningfor a few days on the pi and its ok.   still has higher resource usage than v4-beta4 tho

**Comment by ImagoTrigger** [comment]
maybe wanna do the calibration headless tho that should be changed first

**Comment by DSheirer** [comment]
@ImagoTrigger apologies ... can you please rebase onto latest master.  There was a small change in the ChannelProcessingManager.

Also,
Can you use the same pattern for the modifications in the SDRTrunk class where instead of passing in a constructor (boolean) argument, simply use the static headless check (GraphicsEnvironment.isHeadless()) for the conditional configuration items?

This change set is pretty straightforward and we should be able to merge it.

Code standards:
- Wrap single line code in braces for if/then patterns

**Comment by DSheirer** [comment]
@ImagoTrigger I copied your changes over to a new MR and merged that separately in order to cleanup/squash the git commit history into a single commit: 

https://github.com/DSheirer/sdrtrunk/commit/cebca28b19cebb254c2533ba73d9f925fe8909d6

Closing this PR.

**Comment by ImagoTrigger** [comment]
Thanks!

**Pull request closed without merging**
