### PR TITLE
1113 Update LRRP Protocol With Geo-Fence and Hemisphere Parsing Correction

### PR DESCRIPTION
**Pull request by DSheirer**
Resoves #1113.

Updates LRRP protocol to correctly identify geo-fence positions and to add support for packet type identification.  Corrects issue with N/S and E/W hemisphere calculations.

### CODE REVIEW

**Comment by grharrison583** [comment]
Its now calculating the number correctly, but in the northern hemisphere not south. Transmitting Radio in a known location. Ie 35.XXXXX N where it should be 35.XXXX S. Longitude working correctly.

**Comment by DSheirer** [comment]
@grharrison583  Do you have any bit recordings from this that you could share, so that I can look at how the LRRP messages are structured?  

I went back and tested the parsing code against a large number of recordings I have from Dallas, TX area and the previous pasing code was parsing these locations correctly, so I'm leaning towards reverting these changes.

**Comment by grharrison583** [comment]
Ill get one for you in the next few days. The previous code was parsing the
locations at 55.xxx s in the middle of the ocean, when it should have been
35.xxxx south. Adding the 55.xx onto -90 gave the correct location.

**Comment by grharrison583** [comment]
Can you email me at rplant583@gmail.com and Ill reply with recordings. Thanks.

**Comment by DSheirer** [comment]
Can you also include a relative location, lat and long, or place name to use in validating the locations?  ThanksSent from my Galaxy
-------- Original message --------From: grharrison583 ***@***.***> Date: 11/26/21  7:44 AM  (GMT-05:00) To: DSheirer/sdrtrunk ***@***.***> Cc: Denny Sheirer ***@***.***>, State change ***@***.***> Subject: Re: [DSheirer/sdrtrunk] 1113 Update LRRP Protocol With Geo-Fence and Hemisphere Parsing Correction (PR #1114) 
Can you email me at ***@***.*** and Ill reply with recordings. Thanks.

**Pull request merged**
