### PR TITLE
Add OpenMHz Broadcasting Support

### PR DESCRIPTION
**Pull request by tadscottsmith**
Adds native broadcasting to OpenMHz (https://openmhz.com/) or local instances of trunk-server (https://github.com/openmhz/trunk-server) as requested in #1027.

### CODE REVIEW

**Comment by e850205** [comment]
thank you for this

**Comment by e850205** [comment]
I was able to get OpenMHz working, but I don't see any support for trunk-server. Where do I find those options?

**Comment by tadscottsmith** [comment]
Change the upload API server to your trunk-server instance.

**Comment by e850205** [comment]
By that do you mean just a path to the trunk-server folder?

**Comment by tadscottsmith** [comment]
Nope, the URL to the API portion of your trunk-server instance. Are you sure you're trying to connect the right software? It would be whatever you defined `BACKEND_SERVER` to be in your prod.env file.

**Review by DSheirer — APPROVED** [review]
Great PR!  Thanks for the submission!

**Pull request merged**
