### PR TITLE
Demo DMR parser

### PR DESCRIPTION
**Pull request by maozhenyu123**
Wanna get more test cases to see if there is any bugs. 

Maybe we can mark this code(component) as a "Lab feature" and I want to get more feedbacks from the users. PS. I could add a console window for logging.

### CODE REVIEW

**Comment by 49handyman** [comment]
if you can let me know how to implement on my fork. ill start testing

**Comment by maozhenyu123** [comment]
> if you can let me know how to implement on my fork. ill start testing

You can add a new track on my fork by: 
`git remote add upstream-maozhenyu123 https://github.com/maozhenyu123/sdrtrunk.git`

then just fetch and pull the dmr-function branch, switch to that branch and good to go.

**Comment by maozhenyu123** [comment]
> if you can let me know how to implement on my fork. ill start testing

You can add a new track on my fork by: 
`git remote add upstream-maozhenyu123 https://github.com/maozhenyu123/sdrtrunk.git`

then just fetch and pull the dmr-function branch, switch to that branch and good to go.

**Comment by 49handyman** [comment]
That worked.

do i need AMBE decoder jar? im trying it out but havent found any dmr yet. checking radioreference closer. doesnt seem to be much on amateur band on their website. for metro area. ill see if i can find some samples so i know what they sound like.

**Comment by DSheirer** [comment]
@maozhenyu123 I tested locally against a DMR system that I think is a Motorola Capacity Plus system.  It's sending out periodic bursts.  

I'm getting some decoding in the console window (system.out messages) and a bunch of Null Pointers.  I might create fork your code and submit PR's to you with a couple changes, if you don't mind?

**Comment by maozhenyu123** [comment]
> @maozhenyu123 I tested locally against a DMR system that I think is a Motorola Capacity Plus system. It's sending out periodic bursts.
> 
> I'm getting some decoding in the console window (system.out messages) and a bunch of Null Pointers. I might create fork your code and submit PR's to you with a couple changes, if you don't mind?

Yup, just go ahead.

**Comment by ah1102** [comment]
Does this mean that dmr support will appear in the new release?

**Comment by maozhenyu123** [comment]
> Does this mean that dmr support will appear in the new release?

Probably not, this DMR decoder is still in Phase I.

**Comment by DSheirer** [comment]
@maozhenyu123 My apologies for not helping sooner.  I had to finish up the testing and changes and get 0.5.0 alpha 1 released.

I've cloned your branch, rebased it onto master and am working on some helping out with some of the areas.  As soon as I get the changes stable I'll submit a PR to you.  Denny

**Comment by maozhenyu123** [comment]
> I've cloned your branch, rebased it onto master and am working on some helping out with some of the areas. As soon as I get the changes stable I'll submit a PR to you. Denny

@DSheirer I have changed some params on the LowPassFilter, and now it works better than before. I have also wrote some new codes but did not push them to the repo. I will do that in probably 1 hour, plz fetch new commits when I finished.

**Comment by DSheirer** [comment]
@maozhenyu123 ok

**Comment by maozhenyu123** [comment]
@DSheirer done, you may now fetch the commit I just pushed (branch: dmr-function)

**Comment by ah1102** [comment]
> > Does this mean that dmr support will appear in the new release?
> 
> Probably not, this DMR decoder is still in Phase I.

How long and difficult to add more modes to your DMR decoder?

**Comment by DSheirer** [comment]
@maozhenyu123 fyi, I'm actively working on this.  I made quite a few changes and I'm working through those testing before i push to my feature branch.  cheers, Denny

**Comment by maozhenyu123** [comment]
@DSheirer Yeah I see, Did you see my comment on your commit?https://github.com/DSheirer/sdrtrunk/commit/a876b0f4dc40a2badad76ff792ed1353775f2e8b

**Comment by DSheirer** [comment]
I did see your comment.  I'll have to finish up what I'm working on and then I can rebase.

**Comment by maozhenyu123** [comment]
OK.

**Comment by DSheirer** [comment]
DMR Decoder was merged into master.  Closing this PR.

**Pull request closed without merging**
