### PR TITLE
#1133 Resolves decimation rate too small issue for NBFM decoder.

### PR DESCRIPTION
**Pull request by DSheirer**

### CODE REVIEW

**Comment by ge0metrix** [comment]
Awesome, thanks for the quick turn around!

**Comment by Brad-git-man** [comment]
I am wondering if someone could explain the version update procedure for SDRT?

**Comment by hans109h** [comment]
If you want the latest commits you need to build from the master source code, otherwise you just need to wait until Denny builds and posts a release.  Further discussion on either ways should take place over at the Google Group.  The question has probably already been answered and folks can help more there.

**Comment by Brad-git-man** [comment]
> If you want the latest commits you need to build from the master source code

What I want to know is, when there are public releases, do you have to manually update by backing up & moving your your play lists & TGs or is there some kind of auto upgrade procedure, like most programs have?

**Comment by hans109h** [comment]
It's always a good idea to manually backup, but you don't have to, you can just run the new version.  Denny will usually provide info on if they is a special risk involved, such as not being able to downgrade after a new release.

**Pull request merged**
