### PR TITLE
Enables native Rdio Scanner streaming capabilities.

### PR DESCRIPTION
**Pull request by tadscottsmith**
This enables native streaming to Rdio Scanner. This is my first contribution to to this project, so I am open to suggestions on anything you'd like to see changed. I'm also open to any edits that you would like to make. I followed the existing Broadcastify Calls work as closely as I could.

### CODE REVIEW

**Comment by natecarlson** [comment]
@DSheirer Any chance this could be merged?

**Comment by DSheirer** [comment]
@tadscottsmith Thank you for the PR!

**Comment by Clark985** [comment]
@tadscottsmith this is slick, thanks for building this.

One minor suggestion:  would there by a way to define a filename, so that different instances can be differentiated in the Rdio-scanner console?  

I'm my use case, I have several remote SDRTrunk instances feeding into a central Rdio-scanner instance.  When troubleshooting duplicate traffic or unmatched talkgroups, it's useful to know which instance pushed that call.   I currently do this in SDRTrunk by putting that info into the site name, which gets embedded into the filename that Rdio ingests.

Here's an example from my console.  TG 1228 is my Rdio-scanner stream test.

2023/05/22 10:00:38 newcall: system=2 talkgroup=33203 file=20230522_100036MN_ARMER_McLeod_TRAFFIC__TO_33203_FROM_557978.mp3 success
2023/05/22 10:00:38 newcall: system=2 talkgroup=2700 file=20230522_100036MN_ARMER_CarverScott_TRAFFIC__TO_2700_FROM_110026.mp3 success
2023/05/22 10:00:40 newcall: system=2 talkgroup=33203 file=20230522_100038MN_ARMER_McLeod_TRAFFIC__TO_33203_FROM_557043.mp3 success
2023/05/22 10:00:40 newcall: system=2 talkgroup=2700 file=20230522_100038MN_ARMER_CarverScott_TRAFFIC__TO_2700.mp3 success
2023/05/22 10:00:43 newcall: system=2 talkgroup=25403 file=20230522_100041MN_ARMER_LakeLillianJV_TRAFFIC__TO_25403_FROM_603040.mp3 success
2023/05/22 10:00:44 newcall: system=2 talkgroup=25359 file=20230522_100042MN_ARMER_CarverScott_TRAFFIC__TO_25359_FROM_620298.mp3 success
**2023/05/22 10:00:45 newcall: system=23 talkgroup=1228 file= success**
2023/05/22 10:00:46 newcall: system=2 talkgroup=25403 file=20230522_100044MN_ARMER_LakeLillianJV_TRAFFIC__TO_25403_FROM_106308.mp3 success
2023/05/22 10:00:47 newcall: system=2 talkgroup=25359 file=20230522_100045MN_ARMER_CarverScott_TRAFFIC__TO_25359_FROM_620003.mp3 success
2023/05/22 10:00:50 newcall: system=2 talkgroup=25403 file=20230522_100048MN_ARMER_LakeLillianJV_TRAFFIC__TO_25403_FROM_106308.mp3 success
2023/05/22 10:00:51 newcall: system=2 talkgroup=29500 file=20230522_100049MN_ARMER_HectorJV_TRAFFIC__TO_29500_FROM_716901.mp3 success
2023/05/22 10:00:52 newcall: system=2 talkgroup=29500 file=20230522_100050MN_ARMER_OliviaTS_TRAFFIC__TO_29500_FROM_716901.mp3 duplicate call rejected

**Comment by tadscottsmith** [comment]
The audio recording/file name are actually done upstream from the broadcasting section of the app, and shared between all of the streaming platforms, so I'd defer to the author on that. If you can parse the ID3 tags, there's a lot of information in the "Comment" field.

I've also never used the rdio-scanner centralized feature, but perhaps you could request that he display more details in the logs, such as what downstream instance initially received the call?

**Comment by Clark985** [comment]
That's a good idea - Rdio-scanner is already matching the API key for the Rdio downstream / SDRTrunk Rdio streaming features.  Should be trivial to log the API key name to the console/event viewer.

**Pull request merged**
