### PR TITLE
Headless mode

### PR DESCRIPTION
**Pull request by balleman**
This attempts to address #92.  I have this working in my environment.  Feedback welcome.

### CODE REVIEW

**Comment by n2cr** [comment]
My local county P25 system working great headless on an Odroid C2.  Hope @DSheirer will accept this into master for the next release.  THANKS!!!

**Comment by DSheirer** [comment]
@balleman I'm focused on the DMR decoder at the moment.  I'll get this reviewed shortly.  Thanks very much for the PR!!

**Comment by DSheirer** [comment]
@balleman I just merged in the changes from the DMR decoder branch.  I updated the ProcessingChain class to get rid of the 2 classes that had swing-dependencies and reimplemented those as DecodeEventHistory and MessageHistory.

**Comment by csharpen** [comment]
Any idea when we may see this in the main release? I assume you simply launch with --headless for this functionality, but is there any documentation around configuration while headless? I assume this would require a second machine with a UI, then forklifting over configs and changing device identifiers as needed? Like many others, I'd really like to use this for Broadcastify P25 feed streaming from something lightweight like an Rpi4 without running any X environment.

**Comment by neilharvey94044** [comment]
Any chance of getting this PR up to alpha6?  I tried combining with PR 1040 to see if I could get it working headless with SDRPlay devices on the RPi 4B Ubuntu x64.  It fails with an exception, which I'm assuming is related to the properties I have left over from running alpha6.

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "frequency_rotation_delay" (class io.github.dsheirer.source.config.SourceConfigTunerMultipleFrequency), not marked as ignorable (4 known properties: "type", "preferred_tuner", "source_type", "frequency"])
 at [Source: (sun.nio.ch.ChannelInputStream); line: 7, column: 141] (through reference chain: io.github.dsheirer.playlist.PlaylistV2["channel"]->java.util.ArrayList[0]->io.github.dsheirer.controller.channel.Channel["source_configuration"]->io.github.dsheirer.source.config.SourceConfigTunerMultipleFrequency["frequency_rotation_delay"])

**Comment by n2cr** [comment]
Yes it would be great to get this merged into the main branch!  Missing the ability to keep my system up-to-date.

**Comment by DSheirer** [comment]
Closing.  Headless incorporated in #1191

**Pull request closed without merging**
