### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by ImagoTrigger**
Adds back the latest JavaFX gradle plugin and requests version 17 of the jfx libs in the build process

### CODE REVIEW

**Comment by ImagoTrigger** [comment]
this should help building the project when the machine has a JDK installed that does not include JavaFX

**Comment by thpryrchn** [comment]
This pull request should be merged, as I wasn't able to compile on my Mac without it.

**Comment by pilot51** [comment]
I'm doing regression testing for an NBFM bug introduced in v0.5.0-beta1 and this solved my build issues following 0eec2e7. Installing JDKs with JavaFX didn't help for some reason. IntelliJ saw the packages but gradle didn't.

**Comment by DSheirer** [comment]
Since the build system already accounts for the JavaFX libraries and the required JDK specifies using the version with integrated JavaFX libraries, I'm going to close this PR.

**Pull request closed without merging**
